<definitions name="PublisherService"
    targetNamespace="http://localhost:8000/publisher"
    xmlns:tns="http://localhost:8000/publisher"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- ~~ Structure ~~ -->
    <types>
        <xsd:schema targetNamespace="http://localhost:8000/publisher">
            <xsd:element name="CreatePublisherRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string" />
                        <xsd:element name="origin" type="xsd:string" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="CreatePublisherResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="id" type="string" />
                        <xsd:element name="name" type="string" />
                        <xsd:element name="origin" type="string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </types>
    <message name="CreatePublisherRequestMessage">
        <part name="request" element="tns:CreatePublisherRequest"/>
    </message>
    <message name="CreatePublisherResponseMessage">
        <part name="response" element="tns:CreatePublisherResponse"/>
    </message>
    <portType name="PublisherPortType">
        <operation name="CreatePublisher">
            <input message="tns:CreatePublisherRequestMessage"/>
            <output message="tns:CreatePublisherResponseMessage"/>
        </operation>
    </portType>
    <binding  name="PublisherBinding" type="tns:PublisherPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CreatePublisher">
            <input>
                <soap:body use="encoded" namespace="http://localhost:8000/publisher"
                    encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body use="encoded" namespace="http://localhost:8000/publisher"
                    encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>
    <service name="PublisherService">
        <port name="PublisherPort" binding="tns:PublisherBinding">
            <soap:address location="http://localhost:8000/publisher"/>
        </port>
    </service>
</definitions>